#! /bin/sh

beginDate=946710000 # Jan 1st 2000 MST
timeToBus=1200 # 20 minutes = 5 minute car warmup, 10 minute drive, 5 minute cushion for bus
workWalkTime=420 # 7 minutes

# 8:16 8:31 13:13 13:28 13:43
busLeaveTimes=(946739760 946740660 946757580 946758480 946759380)
# 8:38 8:58 13:32 13:47 14:02
busEndTimes=(946741080 946742280 946758720 946759620 946760520)

desiredTime=$(date -d "Jan 1 2000 ${1} MST" +"%s")
desiredTime=$(expr ${desiredTime} - ${workWalkTime})
endIndex=0

for (( i=${#busLeaveTimes[@]}-1 ; i>=0 ; i--)); do 
	if [ "$desiredTime" -gt "${busEndTimes[$i]}" ]; then
		endIndex=$i
		break
	fi
done

leaveTime=$(expr ${busLeaveTimes[$endIndex]} - $timeToBus)
almFormatTime=$(date -d @${leaveTime} +"%-l%M%P")

firefox "http://cd.justinjc.com/${almFormatTime}" &

leaveTime=$(date -d @${leaveTime} +"%-l:%M %p")
echo -e "#!/bin/sh\nexport leaveTime=\"$leaveTime\"" > /tmp/busTime
