#! /bin/bash

if [ $(pgrep -cx panel) -gt 1 ] ; then
	printf "%s\n" "The panel is already running." >&2
	exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc config top_padding $PANEL_HEIGHT
bspc control --subscribe > "$PANEL_FIFO" &
numMonitors=$(bspc query -M | wc -l)

panel_music() {
	isNotRunning=$(sp eval | grep -c "Spotify is not running.")
	musicCommand="spotify"
	musicString="%{B#448588}%{F#EADAB2}"

	if [ "$isNotRunning" -ne "1" ]; then
		musicCommand="sp play"
		echo \#! /bin/sh > /tmp/song_info 
		sp eval >> /tmp/song_info
		source /tmp/song_info
		if [ ! -z "$SPOTIFY_TITLE" ]; then
			musicString="$musicString $SPOTIFY_TITLE - $SPOTIFY_ARTIST "
		fi
	fi
	
	echo -e "$musicString %{A:sp prev:}\uf049%{A} %{A:$musicCommand:}\uf04b\uf04c%{A} %{A:sp next:}\uf050%{A} %{F-}%{B-}"
}

panel_clock() {
	echo -e "$(clock -f '%a, %h %-e  %H:%M')"
}

panel_bus() {
	if [ ! -f /tmp/busTime ]; then
		return
	fi

	source /tmp/busTime
	
	echo -e "%{F#98D8ED}\uf207 $leaveTime%{F-}"
}

panel_battery() {
	if !(hash acpi 2>/dev/null); then
		return
	fi

	batteryLevel=$(acpi | cut -d ',' -f2 | sed 's/ //g' | sed 's/%//g')
	batteryIcon=""
	if [ "$batteryLevel" -gt "90" ]; then
		batteryIcon="\uf240"
	elif [ "$batteryLevel" -gt "70" ]; then
		batteryIcon="\uf241"
	elif [ "$batteryLevel" -gt "35" ]; then
		batteryIcon="\uf242"
	elif [ "$batteryLevel" -gt "10" ]; then
		batteryIcon="\uf243"
	else
		batteryIcon="\uf244"
	fi

	echo -e "${batteryIcon} ${batteryLevel}%"
}

panel_volume() {
	volStatus=$(amixer get Master | tail -n 1 | cut -d '[' -f 3 | sed 's/].*//g')
	volLevel=$(amixer get Master | tail -n 1 | cut -d '[' -f 2 | sed 's/%.*//g')
	volString="%%{F"

	if [ "$volStatus" == "on" ]; then
		volString="${volString}#ADFF2F}"

		if [ "$volLevel" -eq "0" ]; then
			volString="${volString}\uf026"
		elif [ "$volLevel" -lt "50" ]; then
			volString="${volString}\uf027"
		else
			volString="${volString}\uf028"
		fi
		
	else
		volString="${volString}#CD5C5C}\uf026"
	fi

	printf "${volString} %3d%% %%{F-}" "$volLevel"
}

panel_power() {
	echo -e "%{F#A34D4D}%{A:poweroff:}\uf011 %{A}%{F-}"
}

while true; do
	if [ "$numMonitors" -eq "2" ]; then
		echo "%{S1}%{r}$(panel_bus) $(panel_volume) $(panel_clock) $(panel_power)%{S} %{S0}%{r}$(panel_music)%{S}" > "$PANEL_FIFO"
	else
		echo "%{r}$(panel_battery) $(panel_volume) $(panel_clock) $(panel_power)" > "$PANEL_FIFO"
	fi
	sleep 0.4s
done &

. panel_colors

cat "$PANEL_FIFO" | panel_bar | lemonbar -n "$PANEL_WM_NAME" -g x$PANEL_HEIGHT -f "$PANEL_FONT_FAMILY" -f "$PANEL_ICON_FAMILY" -F "$COLOR_FOREGROUND" -B "$COLOR_BACKGROUND" -a 12 | \
	while true; do read line; eval "$line" & done;

wait
