#! /bin/sh

bspc config border_width        2
bspc config window_gap         30
bspc config top_padding        15

bspc config split_ratio         0.5
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config focused_border_color "#9C6A00"

numMonitors=$(bspc query -M | wc -l)
if [ "$numMonitors" -eq "2" ]; then
	bspc monitor DVI-I-1 -d $(echo -e '\uf108') $(echo -e '\uf120') $(echo -e '\uf145') $(echo -e '\uf11b')
	bspc monitor HDMI-0 -d $(echo -e '\uf0ac') $(echo -e '\uf141') $(echo -e '\uf0c3') $(echo -e '\uf001') 
elif [ "$numMonitors" -eq "1" ]; then
	bspc monitor -d $(echo -e '\uf109') $(echo -e '\uf120') $(echo -e '\uf145') $(echo -e '\uf11b') $(echo -e '\uf0ac') $(echo -e '\uf141') $(echo -e '\uf0c3') $(echo -e '\uf001')
fi

bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a Chromium desktop=^2
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Spotify desktop=^6

panel &
