#! /bin/sh

bspc config border_width        1
bspc config window_gap         20

bspc config split_ratio         0.5
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config click_to_focus		true

bspc config focused_border_color "#d79921"
bspc config normal_border_color	"#282828"
bspc config active_border_color	"#282828"
bspc config presel_feedback_color "#d65d0e"

numMonitors=$(bspc query -M | wc -l)
if [ "$numMonitors" -eq "2" ]; then
	bspc monitor DVI-I-1 -d $(echo -e '\uf108') $(echo -e '\uf120') $(echo -e '\uf145') $(echo -e '\uf11b')
	bspc monitor HDMI-0 -d $(echo -e '\uf0ac') $(echo -e '\uf141') $(echo -e '\uf0c3') $(echo -e '\uf001')
	bspc monitor HDMI-0 -s DVI-I-1
elif [ "$numMonitors" -eq "1" ]; then
	bspc monitor -d $(echo -e '\uf109') $(echo -e '\uf120') $(echo -e '\uf145') $(echo -e '\uf11b') $(echo -e '\uf0ac') $(echo -e '\uf141') $(echo -e '\uf0c3') $(echo -e '\uf001')
fi

export BSPWM_DESKTOP_WALL_WIDTH=2
export BSPWM_DESKTOP_WALL_HEIGHT=2

wmname LG3D # Helps load some GUI Java programs
xdotool behave_screen_edge --quiesce 600 -delay 0 top-right exec vin/notify_info &
compton --config ~/.config/compton.conf -b
